### ISSUE TITLE
Submit to the puppet forge

### ISSUE THREAD

**Issue by solarnz** [rjpearce/puppet-opendkim#13]
Hi there,

This is the best opendkim puppet module that i have found so far.

Is there any possibility on getting it published to the puppet forge?

https://docs.puppet.com/puppet/latest/reference/modules_publishing.html

**Comment by rjpearce** [comment]
Tried in the past but it was very difficult back then, will give it another go.

**Comment by rjpearce** [comment]
Hi, This has been done. Thanks I should have done this ages ago. 
https://forge.puppet.com/rjpearce/opendkim/readme
