### ISSUE TITLE
provide content instead of source for private key

### ISSUE THREAD

**Issue by mc0e** [rjpearce/puppet-opendkim#5]
opendkim::domain expects to be provided with `private_key `, which is used as a `source` attribute for the created file.

This means that the private key has to be provided as a download from the puppetmaster or some other source with relatively little security.  Any host that can connect to the puppetmaster can download it.

I suggest that the option be added to provide `private_key_content` instead, which should be passed as a `content` attribute to the file resource.

**Comment by rjpearce** [comment]
This sounds entirely reasonable but I would like to ensure it remains backwards compatible.

Would this be satisfactory:
* Modify private_key to have a default value: false
* Add the new parameter private_key_content, default value: false

Add some conditionals:
* if private_key and private_key_content are false throw an error
* If private_key is false use private_key_content as the content
* If private_key_content is false use private_key as the source
 
Would you be happy to make these changes and send me a pull request?

**Comment by mc0e** [comment]
I've pretty much got what you describe already, in testing.  I'll put in a pull request when I've verified it's working.

**Comment by rjpearce** [comment]
This has been resolved with thanks to toepi
Please see https://github.com/rjpearce/puppet-opendkim/pull/6
